### ISSUE TITLE
All basic commands should accept file names or a flag `--all` 

### ISSUE THREAD

**Issue by StephanLoor** [MarkusSagen/rejx#5]
My idea is to fix two "issues" at the same time: 
1. At present, `diff` and `clean` can only be applied to all files at once, i.e. they cannot be applied to individual files. 
2. There are two separate commands `fix` and `fix_all`, even though the latter really just applies the former to every .rej file present. 

My proposal would be to do the following:
1. Add an optional flag `--all` to the `fix` command, and make the input variable `rej_file_path` optional (with default value `''`). Typer can be used to implement this.  
2. If the flag `--all` passed, run what is currently `fix_all`. 
3. Remove `fix_all` as a separate command. 
4. If `--all` is not passed, check if `rej_file_path == ''`. If this is the case, then raise an error. Otherwise, apply the current `fix` command.    
5. Apply the same logic to `diff` and `clean`. 

@MarkusSagen if you like these ideas, I can have a go at implementing them myself 😄

**Comment by MarkusSagen** [comment]
💯 Great suggestion! It was not the ideal flow for implementing this before and I think the proposed change is what it should have been from the beginning

@StephanLoor, if you would like to take a stab at it, that would be much appreciated 😃

**Comment by StephanLoor** [comment]
Closed as completed in #6

**Comment by MarkusSagen** [comment]
Included in the `0.2.0` release
